### PR TITLE
Agricola: fixed issue #17

### PR DESCRIPTION
**Pull request by lehenry**
fixed issue #17

Set the pasture background image on the central board only, since it was not clearly readable, while other boards are clear enough in my opinion.
image

### CODE REVIEW

**Comment by shervinsahba** [comment]
Wow, that's great! Thanks for the response! I'll have to check out how you did it, so I can learn to hack CSS better.

**Comment by shervinsahba** [comment]
There's a side board that often gets attached to play as well, especially in 3-5p games, which would benefit from the green pasture background. The sideboard's div id is `left-board`. When a game is started with the optional "Additional Spaces" config, this side board seems to be called `add-board` but there's also an `add-board-holder` that might be relevant.

**Comment by lehenry** [comment]
The trick I use for bugs is to launch the demo game/tutorial (here: https://boardgamearena.com/archive/replay/211220-1500/?table=225356719&player=88007792&comments=#)  - for some reason, those games don't use the custom theme.
Then in developer mode in Firefox (F12) I go to the "Style Editor" tab, add a new style and copy the custom style.
image

I then use the "pick element" tool to select the item where the issue is, see where the issue is (usually, just white text on a white image) - add some CSS in my custom CSS to until it fix the issue. 

The benefit of using the demo page (outside of not having to play a full game to find all issues) is that I can hide the custom CSS to compare with the normal style.

**Comment by shervinsahba** [comment]
Cool! I'm not a web dev so my training is lacking with CSS. I appreciate it!

**Comment by lehenry** [comment]
Tentatively fixed the additional board and left board (only checked on one of them while spectating an active game, that seems to do the trick)

**Comment by shervinsahba** [comment]
Thank you again. I'm going through my games and found a few more instances of white text on light backgrounds. 

Cards in your hand (yellow square button on main board goes to this menu)
cards

Major improvements (red square button on the main board)
improvements

Scoring (star icon button in top-right menu bar)
scoring

Exchange (a cooking pot icon that only appears at the end of a "harvest round". It appears in the pop-up bar where you confirm actions)
exchange

I think that's all the menus. Let me know if you'd rather me fiddle with the code and patch the font color. I really appreciate your help, though!

**Pull request merged**
